import type { CiqualFoodLibraryChunk } from './ciqual-library.types';
import type { OpenNutritionFoodLibraryChunk } from './opennutrition-library.types';

export const CIQUAL_FIXTURE_CHUNK: CiqualFoodLibraryChunk = {
  libraryVersion: '2025',
  source: 'ciqual',
  generatedAt: '2026-09-02T00:00:00.000Z',
  entryCount: 4,
  entries: [
    {
      id: 'ciqual-9001',
      nameFr: 'Œuf, cru',
      category: 'œufs de poule',
      kcal: 143,
      proteinG: 12.8,
      fatG: 9.9,
      carbsG: 0,
      fiberG: 0,
      aliases: ['Egg, raw'],
    },
    {
      id: 'ciqual-9002',
      nameFr: 'Pomme, crue',
      category: 'fruits',
      kcal: 52,
      proteinG: 0,
      fatG: 0,
      carbsG: 11.3,
      fiberG: 0,
      aliases: [],
    },
    {
      id: 'ciqual-9003',
      nameFr: 'Riz cuit',
      category: 'féculents',
      kcal: 130,
      proteinG: 2.7,
      fatG: 0.3,
      carbsG: 28,
      fiberG: 0.4,
      aliases: [],
    },
    {
      id: 'ciqual-9004',
      nameFr: 'Skyr, nature',
      category: 'produits laitiers',
      kcal: 60,
      proteinG: 10,
      fatG: 0.2,
      carbsG: 4,
      fiberG: 0,
      aliases: [],
    },
  ],
};

export const OPENNUTRITION_FIXTURE_CHUNK: OpenNutritionFoodLibraryChunk = {
  libraryVersion: '2025.1',
  source: 'opennutrition',
  generatedAt: '2026-09-02T00:00:00.000Z',
  entryCount: 3,
  entries: [
    {
      id: 'fd_test1',
      name: 'Skyr Nature',
      brand: 'Danone',
      barcode: '3560070467394',
      type: 'grocery',
      kcal: 63,
      proteinG: 10.5,
      fatG: 0.2,
      carbsG: 4.1,
      fiberG: 0,
    },
    {
      id: 'fd_test2',
      name: 'Organic Peanut Butter',
      brand: 'Jif',
      barcode: '0013764027053',
      type: 'grocery',
      kcal: 590,
      proteinG: 25,
      fatG: 50,
      carbsG: 20,
      fiberG: 8,
    },
    {
      id: 'fd_test3',
      name: 'Chicken Breast, Cooked',
      type: 'everyday',
      kcal: 151,
      proteinG: 30.5,
      fatG: 3.2,
      carbsG: 0,
      fiberG: 0,
    },
  ],
};
